"""
mesi_cache_model.py
Behavioral Python model of the 4-core MESI LV1+LV2 cache system.
Acts as the DUT in the Python UVM testbench (no RTL simulator required).

Cache parameters match the SV design defaults:
  - 4-way set associative LV1 (ICache + DCache per core)
  - 14-bit index, 16-bit tag, 2-bit offset
  - LRU replacement (3-bit pseudo-LRU, same algorithm as scoreboard)
  - MESI coherence across 4 cores
  - Infinite backing memory (dict-based)
"""

import logging
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple
from cache_tb_pkg import (
    MesiState, AddrType, BusReqType,
    ASSOC, TAG_WID, INDEX_WID,
    CORRECT_DATA_0, CORRECT_DATA_1,
    addr_parts, addr_to_cache_type,
)

log = logging.getLogger("MESI_MODEL")


# ---------------------------------------------------------------------------
# Cache set structure (mirrors set_t in scoreboard)
# ---------------------------------------------------------------------------

@dataclass
class CacheSet:
    capacity: int = 0
    lru: int = 0                          # 3-bit pseudo-LRU
    tag:   List[int] = field(default_factory=lambda: [0] * ASSOC)
    data:  List[int] = field(default_factory=lambda: [0] * ASSOC)
    state: List[MesiState] = field(
        default_factory=lambda: [MesiState.STATE_I] * ASSOC
    )


# ---------------------------------------------------------------------------
# Helpers: LRU logic (identical to SV scoreboard)
# ---------------------------------------------------------------------------

def lru_get_way(s: CacheSet) -> int:
    """Return the way to replace according to pseudo-LRU."""
    lru = s.lru
    if   lru in (0b000, 0b001): return 0
    elif lru in (0b010, 0b011): return 1
    elif lru in (0b100, 0b110): return 2
    else:                        return 3   # 0b101, 0b111


def lru_update(s: CacheSet, way: int, addr_type: AddrType):
    """Update pseudo-LRU bits after accessing 'way'."""
    if addr_type == AddrType.ICACHE:
        if   way == 0: s.lru = (s.lru & 0b000) | 0b110
        elif way == 1: s.lru = (s.lru & 0b001) | 0b100
        elif way == 2:
            s.lru = (s.lru | 0b001) & 0b011
        else:          # way 3
            s.lru = (s.lru & 0b001) & 0b010  # clear bits
    else:  # DCACHE — matches SV update_lru
        if   way == 0: s.lru = s.lru | 0b110
        elif way == 1: s.lru = (s.lru | 0b100) & 0b101
        elif way == 2: s.lru = (s.lru | 0b001) & 0b011
        else:          s.lru = s.lru & 0b010


def get_free_way(s: CacheSet) -> int:
    """Return the first invalid way (fill order: 3,2,1,0)."""
    for w in (3, 2, 1, 0):
        if s.state[w] == MesiState.STATE_I:
            return w
    return -1


# ---------------------------------------------------------------------------
# Main cache model
# ---------------------------------------------------------------------------

class MesiCacheModel:
    """
    Behavioural model of the 4-core MESI cache hierarchy.

    Public API
    ----------
    read(cpu, address)  -> int          # returns data (fills DUT model)
    write(cpu, address, data) -> None
    last_sbus_packet()  -> dict | None  # system bus packet generated by last op
    """

    NUM_CORES = 4

    def __init__(self):
        # icache[cpu][index] -> CacheSet
        self.icache: List[Dict[int, CacheSet]] = [{} for _ in range(self.NUM_CORES)]
        # dcache[cpu][index] -> CacheSet
        self.dcache: List[Dict[int, CacheSet]] = [{} for _ in range(self.NUM_CORES)]
        # backing memory: {(tag, index): data}
        self.memory: Dict[Tuple[int, int], int] = {}
        # last system-bus event for scoreboard verification
        self._last_sbus: Optional[dict] = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def read(self, cpu: int, address: int) -> int:
        """Perform a read transaction; returns the data value."""
        self._last_sbus = None
        addr_type = addr_to_cache_type(address)
        tag, index, _ = addr_parts(address)

        if addr_type == AddrType.ICACHE:
            return self._icache_read(cpu, address, tag, index)
        else:
            return self._dcache_read(cpu, address, tag, index)

    def write(self, cpu: int, address: int, data: int) -> None:
        """Perform a write transaction (DCache only; ICache write is illegal)."""
        self._last_sbus = None
        addr_type = addr_to_cache_type(address)
        if addr_type == AddrType.ICACHE:
            log.warning(f"CPU{cpu}: Illegal write to ICache addr=0x{address:08x}, ignored")
            return
        tag, index, _ = addr_parts(address)
        self._dcache_write(cpu, address, data, tag, index)

    def last_sbus_packet(self) -> Optional[dict]:
        return self._last_sbus

    # ------------------------------------------------------------------
    # Memory model helpers
    # ------------------------------------------------------------------

    def _mem_read(self, tag: int, index: int, address: int) -> int:
        key = (tag, index)
        if key in self.memory:
            return self.memory[key]
        # Default pre-initialized values (matches SV scoreboard)
        return CORRECT_DATA_1 if (address >> 3) & 1 else CORRECT_DATA_0

    def _mem_write(self, tag: int, index: int, data: int):
        self.memory[(tag, index)] = data

    # ------------------------------------------------------------------
    # Cache lookup helpers
    # ------------------------------------------------------------------

    def _hit_way(self, cache: Dict[int, CacheSet], index: int, tag: int) -> int:
        """Return way index if tag is present and not Invalid, else -1."""
        if index not in cache:
            return -1
        s = cache[index]
        for w in range(ASSOC):
            if s.tag[w] == tag and s.state[w] != MesiState.STATE_I:
                return w
        return -1

    def _alloc_way(self, cache: Dict[int, CacheSet], cpu: int, index: int,
                   addr_type: AddrType, tag: int) -> Tuple['CacheSet', int, bool]:
        """
        Allocate a way for a miss; return (set, way, eviction_was_dirty).
        Updates memory if dirty eviction.
        """
        if index not in cache:
            cache[index] = CacheSet()
        s = cache[index]

        # Fill empty way first
        if s.capacity < ASSOC:
            w = get_free_way(s)
            s.capacity += 1
            return s, w, False

        # LRU eviction
        w = lru_get_way(s)
        dirty_evict = (s.state[w] == MesiState.STATE_M)
        if dirty_evict:
            self._mem_write(s.tag[w], index, s.data[w])
            log.debug(f"CPU{cpu}: dirty evict way{w} tag=0x{s.tag[w]:04x} idx={index}")
        s.state[w] = MesiState.STATE_I
        return s, w, dirty_evict

    # ------------------------------------------------------------------
    # ICache read
    # ------------------------------------------------------------------

    def _icache_read(self, cpu: int, address: int, tag: int, index: int) -> int:
        ic = self.icache[cpu]
        w = self._hit_way(ic, index, tag)

        if w >= 0:
            # Hit
            log.debug(f"CPU{cpu}: ICache HIT  addr=0x{address:08x} way={w}")
            lru_update(ic[index], w, AddrType.ICACHE)
            return ic[index].data[w]

        # Miss — always serviced by L2/memory (ICache is read-only, never shared dirty)
        data = self._mem_read(tag, index, address)
        s, w, _ = self._alloc_way(ic, cpu, index, AddrType.ICACHE, tag)
        s.tag[w]   = tag
        s.data[w]  = data
        s.state[w] = MesiState.STATE_S
        lru_update(s, w, AddrType.ICACHE)

        self._last_sbus = {
            "bus_req_type":    BusReqType.ICACHE_RD,
            "bus_req_proc_num": cpu,
            "req_address":     address & ~0x3,
            "req_serviced_by": "SERV_L2",
            "rd_data":         data,
            "cp_in_cache":     0,
            "shared":          0,
        }
        log.info(f"CPU{cpu}: ICache MISS addr=0x{address:08x} -> data=0x{data:08x} (SERV_L2)")
        return data

    # ------------------------------------------------------------------
    # DCache read
    # ------------------------------------------------------------------

    def _dcache_read(self, cpu: int, address: int, tag: int, index: int) -> int:
        dc = self.dcache

        # Check own cache first
        w = self._hit_way(dc[cpu], index, tag)
        if w >= 0:
            log.debug(f"CPU{cpu}: DCache HIT  addr=0x{address:08x} way={w}")
            lru_update(dc[cpu][index], w, AddrType.DCACHE)
            return dc[cpu][index].data[w]

        # Miss: check other caches (snooping)
        shared = False
        snoop_data = None
        snoop_req  = 0
        for other in range(self.NUM_CORES):
            if other == cpu:
                continue
            ow = self._hit_way(dc[other], index, tag)
            if ow >= 0:
                other_set = dc[other][index]
                snoop_data = other_set.data[ow]
                snoop_req |= (1 << other)
                shared = True
                if other_set.state[ow] == MesiState.STATE_M:
                    # Write-back on snoop
                    self._mem_write(tag, index, snoop_data)
                    other_set.state[ow] = MesiState.STATE_S
                elif other_set.state[ow] == MesiState.STATE_E:
                    other_set.state[ow] = MesiState.STATE_S

        data = snoop_data if snoop_data is not None else self._mem_read(tag, index, address)
        s, w, _ = self._alloc_way(dc[cpu], cpu, index, AddrType.DCACHE, tag)
        s.tag[w]  = tag
        s.data[w] = data
        s.state[w] = MesiState.STATE_S if shared else MesiState.STATE_E
        lru_update(s, w, AddrType.DCACHE)

        self._last_sbus = {
            "bus_req_type":    BusReqType.BUS_RD,
            "bus_req_proc_num": cpu,
            "req_address":     address & ~0x3,
            "bus_req_snoop":   snoop_req,
            "req_serviced_by": "SERV_L2" if not shared else f"SERV_SNOOP",
            "rd_data":         data,
            "cp_in_cache":     int(shared),
            "shared":          int(shared),
        }
        log.info(f"CPU{cpu}: DCache MISS addr=0x{address:08x} shared={shared} -> data=0x{data:08x}")
        return data

    # ------------------------------------------------------------------
    # DCache write
    # ------------------------------------------------------------------

    def _dcache_write(self, cpu: int, address: int, data: int, tag: int, index: int):
        dc = self.dcache
        w = self._hit_way(dc[cpu], index, tag)
        bus_req_type = BusReqType.BUS_RDX

        if w >= 0:
            # Write hit
            s = dc[cpu][index]
            if s.state[w] == MesiState.STATE_S:
                # Shared → need invalidate
                bus_req_type = BusReqType.INVALIDATE
            # Exclusive or Modified: silent upgrade, no bus transaction
            elif s.state[w] in (MesiState.STATE_E, MesiState.STATE_M):
                s.data[w]  = data
                s.state[w] = MesiState.STATE_M
                lru_update(s, w, AddrType.DCACHE)
                log.info(f"CPU{cpu}: DCache WR HIT (E/M) addr=0x{address:08x} data=0x{data:08x}")
                return

            # Invalidate shared copies
            self._invalidate_others(cpu, index, tag)
            s.data[w]  = data
            s.state[w] = MesiState.STATE_M
            lru_update(s, w, AddrType.DCACHE)

            self._last_sbus = {
                "bus_req_type":    bus_req_type,
                "bus_req_proc_num": cpu,
                "req_address":     address & ~0x3,
                "req_serviced_by": "SERV_L2",
                "rd_data":         data,
            }
            log.info(f"CPU{cpu}: DCache WR HIT (S) addr=0x{address:08x} -> INVALIDATE")
            return

        # Write miss: BUS_RDX
        # Check dirty eviction
        evict_data = None; evict_addr = None
        if index in dc[cpu] and dc[cpu][index].capacity >= ASSOC:
            ev_w = lru_get_way(dc[cpu][index])
            ev_s = dc[cpu][index]
            if ev_s.state[ev_w] == MesiState.STATE_M:
                evict_data = ev_s.data[ev_w]
                evict_addr = (ev_s.tag[ev_w] << 16) | (index << 2)
                self._mem_write(ev_s.tag[ev_w], index, evict_data)

        self._invalidate_others(cpu, index, tag)
        s, w, _ = self._alloc_way(dc[cpu], cpu, index, AddrType.DCACHE, tag)
        s.tag[w]  = tag
        s.data[w] = data
        s.state[w] = MesiState.STATE_M
        lru_update(s, w, AddrType.DCACHE)

        self._last_sbus = {
            "bus_req_type":    BusReqType.BUS_RDX,
            "bus_req_proc_num": cpu,
            "req_address":     address & ~0x3,
            "req_serviced_by": "SERV_L2",
            "rd_data":         data,
            "proc_evict_dirty_blk_flag": evict_data is not None,
            "proc_evict_dirty_blk_addr": evict_addr,
            "proc_evict_dirty_blk_data": evict_data,
        }
        log.info(f"CPU{cpu}: DCache WR MISS addr=0x{address:08x} data=0x{data:08x} -> BUS_RDX")

    # ------------------------------------------------------------------
    # Snooping helpers
    # ------------------------------------------------------------------

    def _invalidate_others(self, cpu: int, index: int, tag: int):
        """Invalidate tag in all caches except cpu."""
        for other in range(self.NUM_CORES):
            if other == cpu:
                continue
            ow = self._hit_way(self.dcache[other], index, tag)
            if ow >= 0:
                s = self.dcache[other][index]
                if s.state[ow] == MesiState.STATE_M:
                    self._mem_write(tag, index, s.data[ow])
                s.state[ow] = MesiState.STATE_I
                s.capacity -= 1
                log.debug(f"  -> Invalidated CPU{other} way{ow}")
